version: "2.2"
services:
  provider:
    build:
      context: ./provider  # Or the correct path to your Dockerfile and provider.py
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
  consumer:
    build:
      context: ./consumer  # Or the correct path to your Dockerfile and provider.py
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    ports:
      - "90:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - provider
      - consumer
